#!/usr/bin/env python3
"""Rebuild every stats page, chart, and the root README from records/.

Usage:  python3 scripts/build.py

Each file in records/<event>/YYYY-MM-DD.txt is one PB. The file name gives
the date; the times inside give the average. More than one PB of the same
event on the same day: YYYY-MM-DD_2.txt, YYYY-MM-DD_3.txt, ... (in the order
they happened; the plain name counts as #1).

fast-solves/YYYY-MM-DD[_N].txt holds hand-picked good solves (one solve per
file, same format, reconstruction optional). They get move-count metrics but
no distributions, and never affect PBs. A csTimer export can be
pasted in whole (its header lines are skipped, and a "single: 9.90" or
"avg of 5: 13.53" line is checked against what the script computes).
Two input formats work:

  numbered (with scrambles)       comma-separated (times only)
  1. (14.53)   D' L' U2 ...       15.05, 13.86, (11.38), 17.14
  2. 12.41   F2 U2 F2 ...         13.29, 17.90, 15.59

Parentheses are optional and ignored: the script decides which solves get
trimmed itself. "17.03+" means a +2 already included in 17.03 (csTimer style).
"DNF" / "DNF(14.20)" count as the worst possible solve. Lines starting with #
are notes and appear on the stats page.

Optional reconstruction: lines starting with ">" right under a numbered solve
belong to that solve. Use // for step comments:

  1. 9.90   R2 B2 L2 F D2 ...
  > z2 // inspection
  > D R' F D' // cross
  > U R U' R' // F2L 1
"""

import json
import math
import re
from datetime import date, timedelta
from pathlib import Path
from urllib.parse import quote

import matplotlib

matplotlib.use("Agg")
import matplotlib.dates as mdates
import matplotlib.patches
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats as sps

ROOT = Path(__file__).resolve().parent.parent
RECORDS = ROOT / "records"
STATS = ROOT / "stats"
EVENTS = ["single", "ao5", "ao12", "ao25", "ao50", "ao100"]

# Colors (reference palette, light mode)
SURFACE = "#fcfcfb"
INK = "#0b0b0b"
INK_2 = "#52514e"
GRID = "#e4e3df"
COUNTED = "#2a78d6"  # blue: solves that count toward the average
TRIMMED = "#b9b8b2"  # gray: solves trimmed off the ends
FIT = "#eb6834"  # orange: fitted normal curve
ACCENT = "#1baf7a"  # aqua: KDE / rolling average

HEADER_RE = re.compile(r"^(generated by cstimer|time list:|solves?/total:|session)", re.I)
CLAIM_RE = re.compile(r"^(single|best|avg of \d+|mean of \d+)\s*:\s*(\S+)", re.I)
MOVE_RE = re.compile(r"^([RLUDFB]w?|[rludfbMES])\d*'?$")
TIME_RE = re.compile(r"\(?\s*(DNF(?:\([\d:.]+\))?|[\d:]+\.\d+\+?)\s*\)?", re.I)


# ---------------------------------------------------------------- parsing

def parse_time(tok):
    """'17.03+' -> (17.03, '+2'); 'DNF' -> (inf, 'DNF'); '1:02.50' -> 62.5."""
    tok = tok.strip("() ")
    if tok.upper().startswith("DNF"):
        return math.inf, "DNF"
    penalty = "+2" if tok.endswith("+") else ""
    tok = tok.rstrip("+")
    secs = 0.0
    for part in tok.split(":"):
        secs = secs * 60 + float(part)
    return secs, penalty


def parse_file(path):
    """Returns (solves, notes, claimed). claimed is csTimer's own number, if present."""
    solves, notes, claimed = [], [], None
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or HEADER_RE.match(line):
            continue
        if line.startswith("#"):
            notes.append(line.lstrip("# ").rstrip())
            continue
        if line.startswith(">"):
            if not solves:
                raise SystemExit(f"{path}: reconstruction line before any solve: {line}")
            solves[-1]["recon"].append(line[1:].strip())
            continue
        claim = CLAIM_RE.match(line)
        if claim:
            claimed = parse_time(claim.group(2))[0]
            continue
        numbered = re.match(r"^\d+\.\s+(.*)$", line)
        if numbered:
            rest = numbered.group(1)
            m = TIME_RE.match(rest)
            t, pen = parse_time(m.group(1))
            solves.append({"time": t, "penalty": pen, "scramble": rest[m.end():].strip(),
                           "recon": []})
        elif all(TIME_RE.fullmatch(tok.strip()) for tok in line.split(",") if tok.strip()):
            for tok in line.split(","):
                if tok.strip():
                    t, pen = parse_time(tok)
                    solves.append({"time": t, "penalty": pen, "scramble": "", "recon": []})
        else:
            print(f"warning: {path.name}: skipped unrecognised line: {line}")
    return solves, notes, claimed


def alg_link(scramble, recon):
    """alg.cubing.net link that plays the reconstruction from the scramble."""
    enc = lambda a: quote(a.replace("'", "-").replace(" ", "_"), safe="_-")
    return (f"https://alg.cubing.net/?setup={enc(scramble)}"
            f"&alg={enc(chr(10).join(recon))}&type=reconstruction")


NAME_RE = re.compile(r"^(\d{4}-\d{2}-\d{2})(?:_(\d+))?$")


def file_key(f):
    """'2026-09-25_2' -> (date, 2). Plain '2026-09-25' is #1 that day."""
    m = NAME_RE.match(f.stem)
    if not m:
        raise SystemExit(f"{f}: name must be YYYY-MM-DD.txt or YYYY-MM-DD_N.txt")
    return date.fromisoformat(m.group(1)), int(m.group(2) or 1)


def file_label(f):
    d, n = file_key(f)
    return d.isoformat() + (f" (#{n})" if n > 1 else "")


# Which step a reconstruction line belongs to, from its // comment.
STEP_KEYS = [
    ("Inspection", ("inspection",)),
    ("Cross", ("xxcross", "xcross", "cross")),
    ("F2L", ("f2l", "pair", "slot", "fl pair")),
    ("OLL", ("oll", "coll", "eoll", "ocll")),
    ("PLL", ("pll",)),
    ("LL", ("zbll", "1lll", "last layer", "ll")),
    ("AUF", ("auf",)),
]
LL_STEPS = {"OLL", "PLL", "LL", "AUF"}


def analyze_recon(recon):
    """Per-step move counts and whole-solve metrics from a reconstruction."""
    steps, rotations, skips = [], 0, []
    for line in recon:
        body, _, comment = line.partition("//")
        toks = body.replace("(", " ").replace(")", " ").split()
        moves = sum(bool(MOVE_RE.match(t)) for t in toks)
        rotations += sum(bool(re.match(r"^[xyz]\d*'?$", t)) for t in toks)
        c = comment.strip()
        cat = next((name for name, keys in STEP_KEYS
                    if any(re.search(rf"\b{k}\b", c.lower()) for k in keys)), "Other")
        if "skip" in c.lower():
            skips.append(c)
        steps.append({"name": c or "—", "cat": cat, "moves": moves})
    by = lambda cat: sum(st["moves"] for st in steps if st["cat"] == cat)
    xcross = any("xcross" in st["name"].lower() for st in steps)
    # an xxcross solves two pairs in the "cross" step
    xcross = 2 if any("xxcross" in st["name"].lower() for st in steps) else int(xcross)
    pairs = sum(st["cat"] == "F2L" for st in steps) + xcross
    stm = sum(st["moves"] for st in steps)
    f2l = by("F2L") + by("Cross")
    return {
        "stm": stm, "rotations": rotations, "etm": stm + rotations,
        "cross": by("Cross"), "f2l_pairs_moves": by("F2L"), "pairs": pairs,
        "f2l": f2l, "ll": sum(by(c) for c in LL_STEPS),
        # pairs solved in their own step (not inside an x/xxcross)
        "per_pair": (by("F2L") / (pairs - xcross)) if pairs - xcross else None,
        "skips": skips, "steps": steps, "xcross": xcross,
        "labelled": any(st["cat"] != "Other" for st in steps),
    }


def recon_block(s, heading):
    """Markdown for one reconstructed solve: headline metrics, step table, recon."""
    a = analyze_recon(s["recon"])
    t = s["time"]
    tps = f"{a['stm'] / t:.2f}" if math.isfinite(t) and a["stm"] else "—"
    L = [heading, "",
         f"**Scramble:** `{s['scramble']}`  ",
         f"[▶ play on alg.cubing.net]({alg_link(s['scramble'], s['recon'])})", "",
         "| Moves (STM) | TPS | Rotations | ETM |", "|---|---|---|---|",
         f"| **{a['stm']}** | **{tps}** | {a['rotations']} | {a['etm']} |", ""]
    if a["labelled"]:
        extra = [f"cross {a['cross']}"]
        if a["pairs"]:
            extra.append(f"F2L total {a['f2l']} ({a['pairs']} pairs"
                         + (f", {a['per_pair']:.1f}/pair" if a["per_pair"] else "") + ")")
        extra.append(f"last layer {a['ll']}")
        if a["skips"]:
            extra.append("skips: " + ", ".join(a["skips"]))
        L += ["**Breakdown:** " + " · ".join(extra), ""]
    L += ["```", *s["recon"], "```", ""]
    return L


def recon_section(solves, trimmed=()):
    """Markdown for every solve that has a reconstruction (empty if none do)."""
    L = []
    for i, s in enumerate(solves):
        if s["recon"]:
            L += recon_block(s, f"### Solve {i + 1} — {fmt(s['time'])}")
    return (["## Reconstructions", ""] + L) if L else []


# ---------------------------------------------------------------- stats

def trim_count(n):
    """WCA/csTimer rule: drop 5% of solves (rounded up) from each end."""
    return max(1, math.ceil(n * 0.05))


def average(times):
    """Trimmed average, returns (value, set of trimmed indices)."""
    n = len(times)
    k = trim_count(n)
    order = sorted(range(n), key=lambda i: times[i])
    trimmed = set(order[:k] + order[-k:])
    counted = [times[i] for i in range(n) if i not in trimmed]
    if any(math.isinf(t) for t in counted):
        return math.inf, trimmed
    return round(sum(counted) / len(counted) + 1e-9, 2), trimmed


def describe(times):
    finite = np.array([t for t in times if math.isfinite(t)])
    q1, med, q3 = np.percentile(finite, [25, 50, 75])
    out = {
        "n": len(times),
        "dnf": len(times) - len(finite),
        "mean": finite.mean(),
        "median": med,
        "std": finite.std(ddof=1),
        "min": finite.min(),
        "q1": q1,
        "q3": q3,
        "max": finite.max(),
        "iqr": q3 - q1,
        # Relative spread, so a 10s and a 20s solver can be compared fairly.
        "cv": finite.std(ddof=1) / finite.mean(),  # sigma / mean
        "robust_cv": (q3 - q1) / med,  # IQR / median: ignores blowup solves
        "range": finite.max() - finite.min(),
        "skew": sps.skew(finite, bias=False) if len(finite) > 2 else float("nan"),
        "shapiro_p": sps.shapiro(finite).pvalue if len(finite) >= 8 else float("nan"),
    }
    return out


def fmt(t):
    if math.isinf(t):
        return "DNF"
    if t >= 60:
        return f"{int(t // 60)}:{t % 60:05.2f}"
    return f"{t:.2f}"


# ---------------------------------------------------------------- charts

def time_grid(axes, lo, hi, which="x"):
    """Gridlines on the time axis: solid + labeled every second, plus dotted
    half-seconds when the times are close together (span <= 6 s), labeled too
    when very close (span <= 4 s)."""
    import matplotlib.ticker as mt
    span = hi - lo
    for ax in axes:
        axis = ax.xaxis if which == "x" else ax.yaxis
        axis.set_major_locator(mt.MultipleLocator(1))
        axis.set_major_formatter(mt.FormatStrFormatter("%d"))
        ax.grid(axis=which, which="major", color=GRID, linewidth=0.9, linestyle="-")
        if span <= 6:
            axis.set_minor_locator(mt.MultipleLocator(0.5))
            ax.grid(axis=which, which="minor", color=GRID, linewidth=0.9, linestyle=(0, (2, 3)))
            if span <= 4:
                axis.set_minor_formatter(mt.FormatStrFormatter("%.1f"))
                ax.tick_params(axis=which, which="minor", labelsize=7.5, labelcolor=INK_2)
        ax.set_axisbelow(True)


def style_axes(ax):
    ax.set_facecolor(SURFACE)
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    for side in ("left", "bottom"):
        ax.spines[side].set_color(GRID)
    ax.tick_params(colors=INK_2, labelsize=9)
    ax.grid(axis="y", color=GRID, linewidth=0.8)
    ax.set_axisbelow(True)


def plot_distribution(event, day, times, trimmed, avg, st, out, solves=None):
    finite_idx = [i for i, t in enumerate(times) if math.isfinite(t)]
    counted = [times[i] for i in finite_idx if i not in trimmed]
    cut = [times[i] for i in finite_idx if i in trimmed]
    allt = np.array(counted + cut)

    n = len(times)

    fig, (ax, axb) = plt.subplots(
        2, 1, figsize=(9, 5.4), sharex=True,
        gridspec_kw={"height_ratios": [4, 1], "hspace": 0.08},
    )
    fig.patch.set_facecolor(SURFACE)
    style_axes(ax)

    # Continuous estimate of the distribution: a Gaussian KDE, scaled so the
    # y-axis reads as "solves per second of time" (area under the curve = n).
    # Bandwidth is 0.6x Scott's rule so real clusters aren't smoothed away.
    kde = sps.gaussian_kde(allt)
    kde.set_bandwidth(kde.factor * 0.6)
    bw = kde.factor * allt.std(ddof=1)
    lo, hi = allt.min() - 3 * bw, allt.max() + 3 * bw  # room for the full tails
    xs = np.linspace(lo, hi, 800)
    dens = kde(xs) * len(allt)
    ax.fill_between(xs, dens, color=COUNTED, alpha=0.18, linewidth=0)
    ax.plot(xs, dens, color=COUNTED, linewidth=2,
            label=f"Density of your times (bandwidth {bw:.2f}s)")
    ax.plot(xs, sps.norm.pdf(xs, st["mean"], st["std"]) * len(allt), color=FIT,
            linewidth=1.6, linestyle="--",
            label=f"Normal fit (μ={st['mean']:.2f}, σ={st['std']:.2f})")

    # Rug: one thin tick per solve at its exact time.
    rug_h = dens.max() * 0.07
    ax.vlines(counted, 0, rug_h, color=COUNTED, linewidth=1, label="One tick per solve")
    ax.vlines(cut, 0, rug_h, color=TRIMMED, linewidth=1,
              label=f"Trimmed (best/worst {trim_count(n)})")
    ax.set_ylim(bottom=0)

    ax.axvline(avg, color=INK, linewidth=1.2)
    ax.axvline(st["median"], color=INK, linewidth=1.2, linestyle=":")
    ax.set_ylim(top=ax.get_ylim()[1] * 1.12)  # headroom for the labels
    ymax = ax.get_ylim()[1]
    # Put each label on the outer side of its line so they never collide.
    avg_right = avg >= st["median"]
    ax.text(avg, ymax * 0.98, f" {event} {fmt(avg)} " if avg_right else f"{event} {fmt(avg)} ",
            color=INK, fontsize=9, va="top", ha="left" if avg_right else "right",
            fontweight="bold")
    ax.text(st["median"], ymax * 0.98, f" median {fmt(st['median'])} ", color=INK_2,
            fontsize=9, va="top", ha="right" if avg_right else "left")

    ax.set_ylabel("Solves within a 1-second window", color=INK_2)
    ax.set_title(f"{event} PB · {fmt(avg)} · {day}", loc="left", color=INK,
                 fontsize=13, fontweight="bold", pad=52)
    ax.legend(frameon=False, fontsize=8.5, labelcolor=INK_2, loc="lower left",
              bbox_to_anchor=(0, 1.01), ncol=2)

    # Box plot + every solve as a dot underneath, same x-axis.
    style_axes(axb)
    axb.grid(False)
    time_grid([ax, axb], allt.min(), allt.max())
    ax.set_xlim(lo, hi)
    axb.boxplot(allt, orientation="horizontal", widths=0.55, patch_artist=True, showfliers=False,
                boxprops={"facecolor": "#dbe8f8", "edgecolor": COUNTED},
                medianprops={"color": INK, "linewidth": 1.5},
                whiskerprops={"color": INK_2}, capprops={"color": INK_2})
    jitter = np.random.default_rng(0).uniform(-0.18, 0.18, len(allt))
    colors = [COUNTED] * len(counted) + [TRIMMED] * len(cut)
    axb.scatter(allt, 1 + jitter, s=14, c=colors, edgecolors=SURFACE, linewidths=0.6, zorder=3)
    axb.set_yticks([])
    axb.spines["left"].set_visible(False)
    axb.set_xlabel("Solve time (s)", color=INK_2)

    fig.savefig(out, dpi=150, bbox_inches="tight", facecolor=SURFACE)
    plt.close(fig)


def plot_numberline(event, day, times, trimmed, avg, st, out, solves=None):
    """Small averages (ao5/ao12): every solve as a labeled dot on a number line.

    Dots too close to label side by side stack upward, so clusters form piles.
    The number line itself is shaded by how many solves sit nearby (darker =
    more concentrated), which shows density without a curve going up and down.
    """
    finite = [(t, i) for i, t in enumerate(times) if math.isfinite(t)]
    finite.sort()
    allt = np.array([t for t, _ in finite])
    span = allt.max() - allt.min()
    lo, hi = allt.min() - 0.08 * span - 0.3, allt.max() + 0.08 * span + 0.3
    min_sep = 0.075 * (hi - lo)  # roughly one label's width in data units

    # Stack: each dot takes the lowest level with no neighbor within min_sep.
    levels, placed = [], []  # placed: (x, level)
    for t, _ in finite:
        lvl = 0
        while any(abs(t - x) < min_sep and l == lvl for x, l in placed):
            lvl += 1
        placed.append((t, lvl))
        levels.append(lvl)
    top = max(levels)

    fig, (ax, axb) = plt.subplots(
        2, 1, figsize=(9, 3.6 + 0.55 * top), sharex=True,
        gridspec_kw={"height_ratios": [3 + top, 1], "hspace": 0.12},
    )
    fig.patch.set_facecolor(SURFACE)
    for a in (ax, axb):
        a.set_facecolor(SURFACE)
        for side in ("top", "right", "left"):
            a.spines[side].set_visible(False)
        a.spines["bottom"].set_color(GRID)
        a.tick_params(colors=INK_2, labelsize=9)
        a.set_yticks([])

    # Density-shaded number line (same KDE as the big averages, drawn as color).
    xs = np.linspace(lo, hi, 600)
    kde = sps.gaussian_kde(allt)
    kde.set_bandwidth(kde.factor * 0.6)
    d = kde(xs)
    d = d / d.max()
    cmap = matplotlib.colors.LinearSegmentedColormap.from_list("conc", [SURFACE, COUNTED])
    band_h = 0.32
    ax.imshow(d[np.newaxis, :], extent=(lo, hi, -band_h - 0.25, -0.25), aspect="auto",
              cmap=cmap, vmin=0, vmax=1, interpolation="bilinear", zorder=1)

    # Dots + exact time labels.
    for (t, i), lvl in zip(finite, levels):
        is_cut = i in trimmed
        y = 0.35 + lvl * 0.9
        ax.scatter([t], [y], s=90, zorder=3,
                   facecolors=SURFACE if is_cut else COUNTED,
                   edgecolors=TRIMMED if is_cut else COUNTED, linewidths=2)
        ax.plot([t, t], [-0.25, y], color=TRIMMED if is_cut else COUNTED,
                linewidth=0.8, alpha=0.5, zorder=2)
        pen = "+" if solves and solves[i]["penalty"] == "+2" else ""
        ax.text(t, y + 0.28, f"({fmt(t)}{pen})" if is_cut else fmt(t) + pen,
                ha="center", va="bottom", fontsize=9,
                color=INK_2 if is_cut else INK, fontweight="normal" if is_cut else "bold",
                bbox={"facecolor": SURFACE, "edgecolor": "none", "pad": 1}, zorder=4)

    # Average and median: markers under the shaded line, so nothing crosses the dots.
    base = -band_h - 0.25
    avg_right = avg >= st["median"]
    for x, lab, col, right in [(avg, f"{event} {fmt(avg)}", INK, avg_right),
                               (st["median"], f"median {fmt(st['median'])}", INK_2, not avg_right)]:
        ax.plot([x, x], [base, -0.25], color=col, linewidth=1.5, zorder=2,
                linestyle="-" if col == INK else ":")
        ax.scatter([x], [base - 0.12], marker="^", s=60, color=col, zorder=3)
        ax.text(x, base - 0.3, f" {lab} " if right else f" {lab} ", color=col, fontsize=9,
                va="top", ha="left" if right else "right",
                fontweight="bold" if col == INK else "normal")
    ytop = 0.35 + top * 0.9 + 0.6
    ax.set_ylim(base - 0.75, ytop)
    time_grid([ax, axb], allt.min(), allt.max())
    ax.set_xlim(lo, hi)
    ax.spines["bottom"].set_visible(False)
    ax.tick_params(axis="x", which="both", length=0, labelbottom=False)

    ax.set_title(f"{event} PB · {fmt(avg)} · {day}", loc="left", color=INK,
                 fontsize=13, fontweight="bold", pad=30)
    handles = [
        plt.Line2D([], [], marker="o", ls="", ms=8, color=COUNTED, label="Counted solve"),
        plt.Line2D([], [], marker="o", ls="", ms=8, mfc=SURFACE, mec=TRIMMED, mew=2,
                   label=f"Trimmed (best/worst {trim_count(len(times))})"),
        matplotlib.patches.Patch(color=COUNTED, alpha=0.8,
                                 label="Shaded line: darker = more solves nearby"),
    ]
    ax.legend(handles=handles, frameon=False, fontsize=8.5, labelcolor=INK_2,
              loc="lower left", bbox_to_anchor=(0, 1.0), ncol=3)

    # Box plot for quartiles, same x-axis.
    axb.boxplot(allt, orientation="horizontal", widths=0.55, patch_artist=True,
                showfliers=True,
                boxprops={"facecolor": "#dbe8f8", "edgecolor": COUNTED},
                medianprops={"color": INK, "linewidth": 1.5},
                whiskerprops={"color": INK_2}, capprops={"color": INK_2},
                flierprops={"marker": "o", "markersize": 5, "markerfacecolor": SURFACE,
                            "markeredgecolor": INK_2})
    axb.set_yticks([])
    axb.set_xlabel("Solve time (s)", color=INK_2)

    fig.savefig(out, dpi=150, bbox_inches="tight", facecolor=SURFACE)
    plt.close(fig)


def plot_sequence(event, day, times, trimmed, avg, out):
    n = len(times)
    x = np.arange(1, n + 1)
    y = np.array([t if math.isfinite(t) else np.nan for t in times])

    fig, ax = plt.subplots(figsize=(9, 3.6))
    fig.patch.set_facecolor(SURFACE)
    style_axes(ax)
    colors = [TRIMMED if i in trimmed else COUNTED for i in range(n)]
    if n >= 12:
        w = 5 if n < 50 else 12
        roll = [average(list(y[i - w + 1:i + 1]))[0] if i >= w - 1 else np.nan for i in range(n)]
        ax.plot(x, roll, color=ACCENT, linewidth=2, label=f"Rolling ao{w}")
    ax.scatter(x, y, s=22 if n <= 25 else 14, c=colors, edgecolors=SURFACE, linewidths=0.6,
               zorder=3, label="Solve (gray = trimmed)")
    ax.axhline(avg, color=INK, linewidth=1, linestyle="--")
    ax.text(n + 0.5, avg, f" {event}\n {fmt(avg)}", color=INK, fontsize=8.5, va="center")
    ax.set_xlim(0.5, n + 0.5)
    fin = y[np.isfinite(y)]
    time_grid([ax], fin.min(), fin.max(), which="y")
    ax.set_xlabel("Solve #", color=INK_2)
    ax.set_ylabel("Time (s)", color=INK_2)
    ax.margins(y=0.08)
    ax.set_title(f"{event} · solves in order", loc="left", color=INK, fontsize=12,
                 fontweight="bold", pad=26)
    ax.legend(frameon=False, fontsize=8.5, labelcolor=INK_2, loc="lower left",
              bbox_to_anchor=(0, 1.0), ncol=2)
    fig.savefig(out, dpi=150, bbox_inches="tight", facecolor=SURFACE)
    plt.close(fig)


def plot_progression(history, out):
    """PB value over time, one small panel per event (different scales)."""
    events = [e for e in EVENTS if history.get(e)]
    fig, axes = plt.subplots(1, len(events), figsize=(2.6 * len(events), 2.8), sharey=False)
    axes = np.atleast_1d(axes)
    fig.patch.set_facecolor(SURFACE)
    for ax, ev in zip(axes, events):
        style_axes(ax)
        pts = history[ev][::-1]  # oldest first; same-day PBs keep file order
        ds = [date.fromisoformat(r["day"]) for r in pts]
        vs = [r["average"] for r in pts]
        ax.step(ds, vs, where="post", color=COUNTED, linewidth=2)
        ax.scatter(ds, vs, s=30, color=COUNTED, edgecolors=SURFACE, zorder=3)
        ax.set_title(f"{ev}  {fmt(vs[-1])}", loc="left", color=INK, fontsize=10,
                     fontweight="bold")
        if ds[0] == ds[-1]:  # one PB so far: give the axis a month of room
            ax.set_xlim(ds[0] - timedelta(days=15), ds[0] + timedelta(days=15))
        loc = mdates.AutoDateLocator(minticks=2, maxticks=4)
        ax.xaxis.set_major_locator(loc)
        ax.xaxis.set_major_formatter(mdates.ConciseDateFormatter(loc))
        ax.tick_params(axis="x", labelsize=7.5)
        ax.margins(y=0.3)
    fig.suptitle("PB progression", x=0.01, ha="left", color=INK, fontsize=12,
                 fontweight="bold")
    fig.tight_layout()
    fig.savefig(out, dpi=150, bbox_inches="tight", facecolor=SURFACE)
    plt.close(fig)


# ---------------------------------------------------------------- pages

def session_page(event, day, solves, notes, avg, trimmed, st, prev):
    counted_std = np.std([s["time"] for i, s in enumerate(solves) if i not in trimmed], ddof=1)
    L = [f"# {event} PB — {fmt(avg)}", "", f"**Date:** {day}  "]
    if prev:
        L.append(f"**Previous PB:** {fmt(prev['average'])} ({prev['date']}) · "
                 f"improved by **{prev['average'] - avg:.2f}s**  ")
    L += [f"[← all records](../../../README.md)", ""]
    for note in notes:
        L.append(f"> {note}")
    if notes:
        L.append("")
    L += ["## Stats", "",
          "| | |", "|---|---|",
          f"| **{event} (official, trimmed)** | **{fmt(avg)}** |",
          f"| Solves | {st['n']} (trimmed {trim_count(st['n'])} from each end) |",
          f"| Mean (all solves) | {st['mean']:.2f} |",
          f"| Median | {st['median']:.2f} |",
          f"| Std dev (σ, all solves) | {st['std']:.2f} |",
          f"| Std dev (σ, counted solves only) | {counted_std:.2f} |",
          f"| **Consistency: σ / mean** | **{100 * st['cv']:.1f}%** |",
          f"| Consistency, outlier-proof: IQR / median | {100 * st['robust_cv']:.1f}% |",
          f"| Min / Best | {fmt(st['min'])} |",
          f"| Q1 (25th pct) | {st['q1']:.2f} |",
          f"| Q3 (75th pct) | {st['q3']:.2f} |",
          f"| Max / Worst | {fmt(st['max'])} |",
          f"| IQR (Q3 − Q1) | {st['iqr']:.2f} |",
          f"| Range | {st['range']:.2f} |"]
    if st["dnf"]:
        L.append(f"| DNFs | {st['dnf']} |")
    if st["n"] >= 8:
        L.append(f"| Skewness | {st['skew']:+.2f} |")
        L.append(f"| Shapiro–Wilk p (normality) | {st['shapiro_p']:.3f} |")
    finite = [s["time"] for s in solves if math.isfinite(s["time"])]
    thresholds = [t for t in range(int(min(finite)) + 1, int(max(finite)) + 2)][:6]
    subs = " · ".join(f"sub-{t}: {sum(x < t for x in finite)}" for t in thresholds)
    L += ["", f"**Sub-X counts:** {subs}", ""]
    if st["n"] >= 8:
        L += ["<sub>Skewness > 0 means a longer tail of slow solves (typical for cubing). "
              "Shapiro–Wilk p < 0.05 means the times are unlikely to be normally distributed.</sub>",
              ""]
    L += ["## Distribution", "", "![distribution](distribution.png)", "",
          "## Solves in order", "", "![sequence](sequence.png)", "",
          *recon_section(solves, trimmed),
          "## Solves", "", "| # | Time | Scramble |" if any(s["scramble"] for s in solves)
          else "| # | Time |",
          "|---|---|---|" if any(s["scramble"] for s in solves) else "|---|---|"]
    for i, s in enumerate(solves):
        t = fmt(s["time"]) + ("+" if s["penalty"] == "+2" else "")
        t = f"({t})" if i in trimmed else f"**{t}**"
        row = f"| {i + 1} | {t} |"
        if s["scramble"]:
            row += f" `{s['scramble']}` |"
        L.append(row)
    L += ["", "<sub>Bold = counted, (parentheses) = trimmed. `+` = includes a +2 penalty.</sub>", ""]
    return "\n".join(L)


def single_page(day, solve, notes, prev):
    L = [f"# Single PB — {fmt(solve['time'])}", "", f"**Date:** {day}  "]
    if prev:
        L.append(f"**Previous PB:** {fmt(prev['average'])} ({prev['date']}) · "
                 f"improved by **{prev['average'] - solve['time']:.2f}s**  ")
    L += ["[← all records](../../../README.md)", ""]
    L += [f"> {n}" for n in notes] + ([""] if notes else [])
    L += [f"**Scramble:** `{solve['scramble']}`", ""]
    L += recon_section([solve]) or [
        "_No reconstruction yet. Add `>` lines under the solve in the record file to include one._", ""]
    return "\n".join(L)


def fast_solves_page():
    files = sorted((ROOT / "fast-solves").glob("*.txt"), key=file_key, reverse=True)
    L = ["# Fast solve bank", "",
         "Hand-picked good solves (not PBs, not averages), newest first. "
         "Generated by `scripts/build.py`.", "",
         "[← all records](../README.md)", ""]
    entries = []
    for f in files:
        solves, notes, _ = parse_file(f)
        if len(solves) != 1:
            raise SystemExit(f"{f}: a fast-solve file holds exactly one solve")
        entries.append((f, solves[0], notes))
    recon = [(f, s, analyze_recon(s["recon"])) for f, s, _ in entries if s["recon"]]
    if recon:
        stm = [a["stm"] for _, _, a in recon]
        tps = [a["stm"] / s["time"] for _, s, a in recon]
        L += ["## Across the bank", "",
              "| Solves | Reconstructed | Mean time | Mean moves (STM) | Fewest moves | "
              "Mean TPS | Highest TPS | Mean rotations |", "|---|---|---|---|---|---|---|---|",
              f"| {len(entries)} | {len(recon)} | "
              f"{np.mean([s['time'] for _, s, _ in entries]):.2f} | {np.mean(stm):.1f} | "
              f"{min(stm)} | {np.mean(tps):.2f} | {max(tps):.2f} | "
              f"{np.mean([a['rotations'] for _, _, a in recon]):.1f} |", ""]
        crosses = [a["cross"] for _, _, a in recon if a["labelled"] and a["cross"]]
        pp = [a["per_pair"] for _, _, a in recon if a["per_pair"]]
        lls = [a["ll"] for _, _, a in recon if a["labelled"] and a["ll"]]
        if crosses or pp or lls:
            L += ["| Mean cross | Mean moves per F2L pair | Mean last layer |", "|---|---|---|",
                  f"| {np.mean(crosses):.1f} | {np.mean(pp):.1f} | {np.mean(lls):.1f} |"
                  .replace("nan", "—"), ""]
    if entries:
        L += ["## All fast solves", "",
              "| Date | Time | Moves (STM) | TPS | Rotations | Cross | Moves/pair | LL | Notes |",
              "|---|---|---|---|---|---|---|---|---|"]
        for f, s, notes in entries:
            a = analyze_recon(s["recon"]) if s["recon"] else None
            anchor = "#" + re.sub(r"[^a-z0-9 -]", "", f"{file_label(f)} {fmt(s['time'])}"
                                  .lower()).replace(" ", "-")
            cells = ([str(a["stm"]), f"{a['stm'] / s['time']:.2f}", str(a["rotations"]),
                      str(a["cross"]) if a["labelled"] else "—",
                      f"{a['per_pair']:.1f}" if a["per_pair"] else "—",
                      str(a["ll"]) if a["labelled"] else "—"] if a else ["—"] * 6)
            L.append(f"| [{file_label(f)}]({anchor}) | **{fmt(s['time'])}** | "
                     + " | ".join(cells) + f" | {'; '.join(notes)} |")
        L.append("")
        for f, s, notes in entries:
            heading = f"### {file_label(f)} — {fmt(s['time'])}"
            if s["recon"]:
                L += recon_block(s, heading)
            else:
                L += [heading, "", f"**Scramble:** `{s['scramble']}`", "",
                      "_No reconstruction._", ""]
            L += [f"> {n}" for n in notes] + ([""] if notes else [])
    else:
        L += ["_No fast solves yet._", ""]
    return "\n".join(L), len(entries)


def readme(history, n_fast=0):
    L = ["# 3x3 PBs", "",
         "Personal-best averages, with the full solve list and stats behind each one. "
         "New here? [What's in this repo →](ABOUT.md)",
         "Generated by `scripts/build.py` — don't edit this file by hand.", "",
         "## Current PBs", "",
         "| Event | PB | Date | Stats |", "|---|---|---|---|"]
    for ev in EVENTS:
        if history.get(ev):
            cur = history[ev][0]
            L.append(f"| **{ev}** | **{fmt(cur['average'])}** | {cur['date']} | "
                     f"[details]({cur['page']}) |")
    L += ["", f"**[Fast solve bank →](fast-solves/README.md)** ({n_fast} solve{'s' if n_fast != 1 else ''})", "",
          "![PB progression](stats/progression.png)", "", "## PB history", "",
          "Newest first. Each new PB pushes the older ones down.", ""]
    for ev in EVENTS:
        rows = history.get(ev)
        if not rows:
            continue
        L += [f"### {ev}", "", "| Date | Time | Improvement | σ | σ / mean | Stats |",
              "|---|---|---|---|---|---|"]
        for i, r in enumerate(rows):
            older = rows[i + 1] if i + 1 < len(rows) else None
            imp = f"−{older['average'] - r['average']:.2f}" if older else "first recorded"
            t = f"**{fmt(r['average'])}**" if i == 0 else fmt(r["average"])
            sd = "—" if r["std"] is None else f"{r['std']:.2f}"
            cv = "—" if r["cv"] is None else f"{100 * r['cv']:.1f}%"
            L.append(f"| {r['date']} | {t} | {imp} | {sd} | {cv} | [details]({r['page']}) |")
        L.append("")
    return "\n".join(L)


# ---------------------------------------------------------------- main

def main():
    history = {}
    for ev in EVENTS:
        files = sorted((RECORDS / ev).glob("*.txt"), key=file_key)
        rows, prev = [], None
        for f in files:  # oldest first, so each knows the PB before it
            day = file_label(f)  # "2026-09-25", or "2026-09-25 (#2)" for a same-day repeat
            solves, notes, claimed = parse_file(f)
            want = 1 if ev == "single" else int(ev[2:])
            if len(solves) != want:
                raise SystemExit(f"{f}: expected {want} solves, found {len(solves)}")
            times = [s["time"] for s in solves]
            avg, trimmed = (times[0], set()) if ev == "single" else average(times)
            if claimed is not None and abs(claimed - avg) > 0.005:
                print(f"warning: {f.name}: csTimer says {fmt(claimed)}, computed {fmt(avg)}")
            if prev and avg >= prev["average"]:
                print(f"warning: {f.name} ({fmt(avg)}) is not faster than {prev['date']} "
                      f"({fmt(prev['average'])})")

            outdir = STATS / ev / f.stem
            outdir.mkdir(parents=True, exist_ok=True)
            row = {"date": day, "day": file_key(f)[0].isoformat(), "average": avg, "std": None, "cv": None,
                   "page": f"stats/{ev}/{f.stem}/README.md",
                   "recon": any(s["recon"] for s in solves)}
            if ev == "single":
                (outdir / "README.md").write_text(single_page(day, solves[0], notes, prev))
                rows.append(row)
                prev = row
                print(f"{ev:>6}  {day}  {fmt(avg)}")
                continue

            st = describe(times)
            row["std"], row["cv"] = st["std"], st["cv"]
            plot = plot_numberline if len(times) <= 12 else plot_distribution
            plot(ev, day, times, trimmed, avg, st, outdir / "distribution.png", solves=solves)
            plot_sequence(ev, day, times, trimmed, avg, outdir / "sequence.png")
            (outdir / "README.md").write_text(
                session_page(ev, day, solves, notes, avg, trimmed, st, prev))
            (outdir / "stats.json").write_text(json.dumps(
                {"event": ev, "date": day, "average": avg,
                 **{k: (round(float(v), 4) if isinstance(v, (float, np.floating)) else int(v))
                    for k, v in st.items()},
                 "times": [None if math.isinf(t) else t for t in times]}, indent=2))

            rows.append(row)
            prev = row
            print(f"{ev:>6}  {day}  {fmt(avg)}")
        history[ev] = rows[::-1]  # newest first

    plot_progression(history, STATS / "progression.png")
    (ROOT / "fast-solves").mkdir(exist_ok=True)
    page, n_fast = fast_solves_page()
    (ROOT / "fast-solves" / "README.md").write_text(page)
    (ROOT / "README.md").write_text(readme(history, n_fast))


if __name__ == "__main__":
    main()
